const $=s=>document.querySelector(s),audio=$('#audio'),results=$('#results');let tracks=[],idx=-1,waveToken=0;
const world={
'África':['Todo África','Argelia','Angola','Benín','Botsuana','Burkina Faso','Burundi','Cabo Verde','Camerún','Chad','Comoras','Costa de Marfil','Egipto','Eritrea','Esuatini','Etiopía','Gabón','Gambia','Ghana','Guinea','Guinea-Bisáu','Guinea Ecuatorial','Kenia','Lesoto','Liberia','Libia','Madagascar','Malaui','Malí','Marruecos','Mauricio','Mauritania','Mozambique','Namibia','Níger','Nigeria','República Centroafricana','República Democrática del Congo','República del Congo','Ruanda','Santo Tomé y Príncipe','Senegal','Seychelles','Sierra Leona','Somalia','Sudáfrica','Sudán','Sudán del Sur','Tanzania','Togo','Túnez','Uganda','Yibuti','Zambia','Zimbabue'],
'América':['Toda América','Antigua y Barbuda','Argentina','Bahamas','Barbados','Belice','Bolivia','Brasil','Canadá','Chile','Colombia','Costa Rica','Cuba','Dominica','Ecuador','El Salvador','Estados Unidos','Granada','Guatemala','Guyana','Haití','Honduras','Jamaica','México','Nicaragua','Panamá','Paraguay','Perú','República Dominicana','San Cristóbal y Nieves','Santa Lucía','San Vicente y las Granadinas','Surinam','Trinidad y Tobago','Uruguay','Venezuela'],
'Asia':['Toda Asia','Afganistán','Arabia Saudita','Armenia','Azerbaiyán','Bangladés','Baréin','Bután','Brunéi','Camboya','Catar','China','Corea del Norte','Corea del Sur','Emiratos Árabes Unidos','Filipinas','Georgia','India','Indonesia','Irak','Irán','Israel','Japón','Jordania','Kazajistán','Kirguistán','Kuwait','Laos','Líbano','Malasia','Maldivas','Mongolia','Myanmar','Nepal','Omán','Pakistán','Palestina','Singapur','Siria','Sri Lanka','Tailandia','Tayikistán','Timor Oriental','Turkmenistán','Turquía','Uzbekistán','Vietnam','Yemen'],
'Europa':['Toda Europa','Albania','Alemania','Andorra','Austria','Bélgica','Bielorrusia','Bosnia y Herzegovina','Bulgaria','Chequia','Chipre','Croacia','Dinamarca','Eslovaquia','Eslovenia','España','Estonia','Finlandia','Francia','Grecia','Hungría','Irlanda','Islandia','Italia','Letonia','Liechtenstein','Lituania','Luxemburgo','Macedonia del Norte','Malta','Moldavia','Mónaco','Montenegro','Noruega','Países Bajos','Polonia','Portugal','Reino Unido','Rumania','Rusia','San Marino','Serbia','Suecia','Suiza','Ucrania','Vaticano'],
'Oceanía':['Toda Oceanía','Australia','Fiyi','Islas Marshall','Islas Salomón','Kiribati','Micronesia','Nauru','Nueva Zelanda','Palaos','Papúa Nueva Guinea','Samoa','Tonga','Tuvalu','Vanuatu']};
const english={Turquía:'Turkey Turkish Ottoman Constantinople Istanbul Anatolia',México:'Mexico Mexican',Egipto:'Egypt Egyptian Cairo',Grecia:'Greece Greek',Japón:'Japan Japanese',Brasil:'Brazil Brazilian',Alemania:'Germany German',España:'Spain Spanish',Francia:'France French',Italia:'Italy Italian',India:'India Indian','Estados Unidos':'USA American United States','Reino Unido':'Britain British England UK','Países Bajos':'Netherlands Dutch',Etiopía:'Ethiopia Ethiopian',Irán:'Iran Persian Persia',Irak:'Iraq Iraqi',China:'China Chinese',Rusia:'Russia Russian'};
const bpmCache=JSON.parse(localStorage.getItem('dvniel-bpm')||'{}'),favs=new Set(JSON.parse(localStorage.getItem('dvniel-favs')||'[]'));
function init(){for(let y=1900;y<=2020;y+=10){let o=document.createElement('option');o.value=y;o.textContent=`${y}–${Math.min(y+9,2026)}`;if(y===1920)o.selected=true;$('#decade').append(o)}Object.keys(world).forEach((x,i)=>$('#continent').add(new Option(x,x,i===2,i===2)));fillCountries();$('#country').value='Turquía'}
function fillCountries(){let c=$('#continent').value||'Asia';$('#country').innerHTML='';world[c].forEach(x=>$('#country').add(new Option(x,x)))}$('#continent').onchange=fillCountries;
function status(t,live=false){$('#status').textContent=t;$('.status').classList.toggle('live',live)}
function geoQuery(){let c=$('#country').value,cont=$('#continent').value;if(c.startsWith('Todo')||c.startsWith('Toda'))return cont;let terms=english[c]||c;return `(${terms.split(' ').map(x=>`"${x}"`).join(' OR ')} OR "${c}")`}
function query(){let d=+$('#decade').value,end=Math.min(d+9,2026);return `mediatype:audio AND date:[${d}-01-01 TO ${end}-12-31] AND ${geoQuery()}`}
async function search(){status('BUSCANDO EN EL ARCHIVO…',true);results.innerHTML='<p class="empty">Sintonizando el mundo…</p>';tracks=[];idx=-1;let url=`https://archive.org/advancedsearch.php?q=${encodeURIComponent(query())}&fl[]=identifier&fl[]=title&fl[]=creator&fl[]=date&rows=50&page=${1+Math.floor(Math.random()*3)}&output=json`;try{let j=await fetch(url).then(r=>r.json()),docs=(j.response?.docs||[]).sort(()=>Math.random()-.5);for(const doc of docs.slice(0,22)){try{let m=await fetch(`https://archive.org/metadata/${encodeURIComponent(doc.identifier)}`).then(x=>x.json()),f=(m.files||[]).find(x=>/\.mp3$/i.test(x.name||'')&&!/64kb|spectrogram/i.test(x.name||''))||(m.files||[]).find(x=>/\.(mp3|ogg)$/i.test(x.name||''));if(!f)continue;tracks.push({id:doc.identifier,title:doc.title||m.metadata?.title||'Sin título',artist:doc.creator||m.metadata?.creator||'Artista desconocido',date:String(doc.date||m.metadata?.date||'').slice(0,4),rights:m.metadata?.licenseurl||m.metadata?.rights||m.metadata?.usage||'',url:`https://archive.org/download/${encodeURIComponent(doc.identifier)}/${f.name.split('/').map(encodeURIComponent).join('/')}`});if(tracks.length>=12)break}catch{}}render();if(tracks.length){load(0);status(`${tracks.length} HALLAZGOS`,false)}else status('SIN RESULTADOS · PRUEBA OTRO LUGAR O ÉPOCA')}catch{status('NO SE PUDO CONECTAR AL ARCHIVO');results.innerHTML='<p class="empty">La fuente no respondió. Intenta de nuevo.</p>'}}
function render(){if(!tracks.length){results.innerHTML='<p class="empty">No encontramos audio reproducible.</p>';return}let lo=+$('#bpmMin').value,hi=+$('#bpmMax').value;results.innerHTML=tracks.map((t,i)=>{let b=bpmCache[t.id],dim=b&&(b<lo||b>hi)?' out':'';return `<div class="track${dim}" data-i="${i}"><div><b>${esc(t.title)}</b><small>${esc(Array.isArray(t.artist)?t.artist.join(', '):t.artist)}${t.date?' · '+t.date:''}</small></div><span class="cached">${b?Math.round(b)+' BPM':''}</span></div>`}).join('');document.querySelectorAll('.track').forEach(x=>x.onclick=()=>load(+x.dataset.i,true))}
function load(i,autoplay=false){if(!tracks.length)return;idx=(i+tracks.length)%tracks.length;let t=tracks[idx];audio.src=t.url;$('#title').textContent=t.title;$('#artist').textContent=`${Array.isArray(t.artist)?t.artist.join(', '):t.artist}${t.date?' · '+t.date:''}`;$('#year').textContent=$('#decade').selectedOptions[0].textContent;$('#place').textContent=$('#country').value.toUpperCase();$('#source').href=`https://archive.org/details/${encodeURIComponent(t.id)}`;$('#rights').textContent=t.rights?`Derechos/fuente: ${t.rights}`:'Escuchar ≠ permiso para samplear. Consulta los derechos de esta grabación.';$('#bpm').textContent=bpmCache[t.id]?Math.round(bpmCache[t.id]):'—';$('#fav').classList.toggle('active',favs.has(t.id));$('#fav').textContent=favs.has(t.id)?'♥ FAVORITO':'♡ FAVORITO';$('#seek').value=0;$('#currentTime').textContent='0:00';drawBlank();makeWave(t.url,++waveToken);if(autoplay)audio.play().catch(()=>{})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(s){if(!isFinite(s))return'0:00';return`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function drawBlank(){let c=$('#waveform'),d=devicePixelRatio||1,w=c.clientWidth||600,h=c.clientHeight||74;c.width=w*d;c.height=h*d;let x=c.getContext('2d');x.scale(d,d);x.strokeStyle='#403d37';x.beginPath();for(let i=0;i<w;i+=5){let a=5+Math.random()*12;x.moveTo(i,h/2-a);x.lineTo(i,h/2+a)}x.stroke()}
async function makeWave(url,token){try{let ab=await fetch(url).then(r=>r.arrayBuffer());if(token!==waveToken)return;let ctx=new(window.AudioContext||window.webkitAudioContext)(),buf=await ctx.decodeAudioData(ab.slice(0)),data=buf.getChannelData(0),c=$('#waveform'),d=devicePixelRatio||1,w=c.clientWidth||600,h=c.clientHeight||74;c.width=w*d;c.height=h*d;let g=c.getContext('2d');g.scale(d,d);g.clearRect(0,0,w,h);g.strokeStyle='#d8d2c5';g.beginPath();let bins=Math.max(1,Math.floor(w/3)),step=Math.max(1,Math.floor(data.length/bins));for(let i=0;i<bins;i++){let peak=0,start=i*step;for(let k=start;k<Math.min(start+step,data.length);k+=Math.max(1,Math.floor(step/80)))peak=Math.max(peak,Math.abs(data[k]));let x=i*w/bins,a=Math.max(2,peak*h*.46);g.moveTo(x,h/2-a);g.lineTo(x,h/2+a)}g.stroke();ctx.close()}catch{}}
$('#waveWrap').onclick=e=>{if(!audio.duration)return;let r=e.currentTarget.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*audio.duration};$('#seek').oninput=e=>{if(audio.duration)audio.currentTime=(e.target.value/1000)*audio.duration};audio.ontimeupdate=()=>{let p=audio.duration?audio.currentTime/audio.duration:0;$('#seek').value=Math.round(p*1000);$('#waveCursor').style.width=`${p*100}%`;$('#currentTime').textContent=fmt(audio.currentTime)};audio.onloadedmetadata=()=>$('#duration').textContent=fmt(audio.duration);
$('#travel').onclick=search;$('#next').onclick=()=>load(idx+1,true);$('#prev').onclick=()=>load(idx-1,true);$('#random').onclick=()=>tracks.length&&load(Math.floor(Math.random()*tracks.length),true);$('#play').onclick=()=>{if(!audio.src)return search();audio.paused?audio.play():audio.pause()};audio.onplay=()=>{$('#play').textContent='Ⅱ';$('.record').classList.add('playing');status('REPRODUCIENDO',true)};audio.onpause=()=>{$('#play').textContent='▶';$('.record').classList.remove('playing')};audio.onended=()=>load(idx+1,true);
$('#fav').onclick=()=>{if(idx<0)return;let id=tracks[idx].id;favs.has(id)?favs.delete(id):favs.add(id);localStorage.setItem('dvniel-favs',JSON.stringify([...favs]));load(idx)};
$('#analyze').onclick=async()=>{if(idx<0)return;let t=tracks[idx];status('ANALIZANDO PULSO…',true);try{let buf=await fetch(t.url).then(r=>r.arrayBuffer()),ctx=new(window.AudioContext||window.webkitAudioContext)(),decoded=await ctx.decodeAudioData(buf),data=decoded.getChannelData(0),sr=decoded.sampleRate,step=Math.max(1,Math.floor(sr/200)),env=[];for(let i=0;i<data.length;i+=step){let s=0;for(let k=i;k<Math.min(i+step,data.length);k++)s+=Math.abs(data[k]);env.push(s/step)}let mean=env.reduce((a,b)=>a+b,0)/env.length,peaks=[];for(let i=1;i<env.length-1;i++)if(env[i]>mean*2.1&&env[i]>env[i-1]&&env[i]>=env[i+1]&&(!peaks.length||i-peaks.at(-1)>12))peaks.push(i);let hist={};for(let i=1;i<peaks.length;i++){let b=60*200/(peaks[i]-peaks[i-1]);while(b<60)b*=2;while(b>180)b/=2;hist[Math.round(b)]=(hist[Math.round(b)]||0)+1}let best=Object.entries(hist).sort((a,b)=>b[1]-a[1])[0];if(!best)throw 0;bpmCache[t.id]=+best[0];localStorage.setItem('dvniel-bpm',JSON.stringify(bpmCache));$('#bpm').textContent=best[0];render();status('BPM ESTIMADO',false);ctx.close()}catch{status('BPM NO DISPONIBLE PARA ESTA PISTA')}};init();drawBlank();