const $=s=>document.querySelector(s);const audio=$('#audio'),results=$('#results');let tracks=[],idx=-1;
const aliases={turkey:'(Turkey OR Turkish OR Ottoman OR Constantinople OR Istanbul OR Anatolia)',egypt:'(Egypt OR Egyptian OR Cairo)',greece:'(Greece OR Greek)',india:'(India OR Indian)',mexico:'(Mexico OR Mexican)',japan:'(Japan OR Japanese)',brazil:'(Brazil OR Brazilian)',westafrica:'("West Africa" OR Ghana OR Senegal OR Nigeria OR Mali)',easterneurope:'("Eastern Europe" OR Romania OR Bulgaria OR Hungary OR Poland OR Yugoslavia)',world:'*'};
const names={turkey:'TURQUÍA',egypt:'EGIPTO',greece:'GRECIA',india:'INDIA',mexico:'MÉXICO',japan:'JAPÓN',brazil:'BRASIL',westafrica:'ÁFRICA OCC.',easterneurope:'EUROPA OR.',world:'MUNDO'};
const bpmCache=JSON.parse(localStorage.getItem('dvniel-bpm')||'{}'),favs=new Set(JSON.parse(localStorage.getItem('dvniel-favs')||'[]'));
function status(t,live=false){$('#status').textContent=t;$('.status').classList.toggle('live',live)}
function query(){const d=+$ ('#decade').value,end=d+9,c=$('#country').value,geo=aliases[c];return `mediatype:audio AND date:[${d}-01-01 TO ${end}-12-31]${geo==='*'?'':` AND ${geo}`}`}
async function search(){status('BUSCANDO EN EL ARCHIVO…',true);results.innerHTML='<p class="empty">Sintonizando archivos históricos…</p>';tracks=[];idx=-1;const q=encodeURIComponent(query());const url=`https://archive.org/advancedsearch.php?q=${q}&fl[]=identifier&fl[]=title&fl[]=creator&fl[]=date&rows=40&page=${1+Math.floor(Math.random()*4)}&output=json`;
try{const r=await fetch(url);if(!r.ok)throw Error('search');const j=await r.json();const docs=(j.response?.docs||[]).sort(()=>Math.random()-.5);for(const doc of docs.slice(0,18)){try{const m=await fetch(`https://archive.org/metadata/${encodeURIComponent(doc.identifier)}`).then(x=>x.json());const f=(m.files||[]).find(x=>/\.mp3$/i.test(x.name||'')&&!/64kb|spectrogram|vbr/i.test(x.name||''))||(m.files||[]).find(x=>/\.(mp3|ogg)$/i.test(x.name||''));if(!f)continue;tracks.push({id:doc.identifier,title:doc.title||m.metadata?.title||'Grabación sin título',artist:doc.creator||m.metadata?.creator||'Artista desconocido',date:String(doc.date||m.metadata?.date||'').slice(0,4),file:f.name,rights:m.metadata?.licenseurl||m.metadata?.rights||m.metadata?.usage||'',url:`https://archive.org/download/${encodeURIComponent(doc.identifier)}/${f.name.split('/').map(encodeURIComponent).join('/')}`});if(tracks.length>=10)break}catch(e){}}
render();if(tracks.length){load(0);status(`${tracks.length} HALLAZGOS`,false)}else status('SIN RESULTADOS · PRUEBA OTRA ÉPOCA',false)}catch(e){status('NO SE PUDO CONECTAR AL ARCHIVO',false);results.innerHTML='<p class="empty">Internet Archive no respondió. Intenta de nuevo.</p>'}}
function render(){if(!tracks.length){results.innerHTML='<p class="empty">No encontramos audio reproducible.</p>';return}results.innerHTML=tracks.map((t,i)=>`<div class="track" data-i="${i}"><div><b>${esc(t.title)}</b><small>${esc(String(t.artist))}${t.date?' · '+t.date:''}</small></div><span class="cached">${bpmCache[t.id]?Math.round(bpmCache[t.id])+' BPM':''}</span></div>`).join('');document.querySelectorAll('.track').forEach(x=>x.onclick=()=>load(+x.dataset.i,true))}
function load(i,autoplay=false){if(!tracks.length)return;idx=(i+tracks.length)%tracks.length;const t=tracks[idx];audio.src=t.url;$('#title').textContent=t.title;$('#artist').textContent=`${Array.isArray(t.artist)?t.artist.join(', '):t.artist}${t.date?' · '+t.date:''}`;$('#year').textContent=$('#decade').value+'s';$('#place').textContent=names[$('#country').value];$('#source').href=`https://archive.org/details/${encodeURIComponent(t.id)}`;$('#rights').textContent=t.rights?`Derechos/fuente: ${t.rights}`:'Escuchar ≠ permiso para samplear. Consulta los derechos de esta grabación en la fuente.';$('#bpm').textContent=bpmCache[t.id]?Math.round(bpmCache[t.id]):'—';$('#fav').classList.toggle('active',favs.has(t.id));$('#fav').textContent=favs.has(t.id)?'♥ FAVORITO':'♡ FAVORITO';if(autoplay)audio.play().catch(()=>{})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#travel').onclick=search;$('#next').onclick=()=>load(idx+1,true);$('#prev').onclick=()=>load(idx-1,true);$('#random').onclick=()=>tracks.length&&load(Math.floor(Math.random()*tracks.length),true);$('#play').onclick=()=>{if(!audio.src){search();return}audio.paused?audio.play():audio.pause()};audio.onplay=()=>{$('#play').textContent='Ⅱ';$('.record').classList.add('playing');status('REPRODUCIENDO',true)};audio.onpause=()=>{$('#play').textContent='▶';$('.record').classList.remove('playing')};audio.onended=()=>load(idx+1,true);
$('#fav').onclick=()=>{if(idx<0)return;const id=tracks[idx].id;favs.has(id)?favs.delete(id):favs.add(id);localStorage.setItem('dvniel-favs',JSON.stringify([...favs]));load(idx,false)};
$('#analyze').onclick=async()=>{if(idx<0)return;const t=tracks[idx];status('ANALIZANDO PULSO…',true);try{const buf=await fetch(t.url).then(r=>r.arrayBuffer()),ctx=new (window.AudioContext||window.webkitAudioContext)(),decoded=await ctx.decodeAudioData(buf),data=decoded.getChannelData(0),sr=decoded.sampleRate,step=Math.max(1,Math.floor(sr/200)),env=[];for(let i=0;i<data.length;i+=step){let s=0;for(let k=i;k<Math.min(i+step,data.length);k++)s+=Math.abs(data[k]);env.push(s/step)}let mean=env.reduce((a,b)=>a+b,0)/env.length,peaks=[];for(let i=1;i<env.length-1;i++)if(env[i]>mean*2.1&&env[i]>env[i-1]&&env[i]>=env[i+1]&&(!peaks.length||i-peaks.at(-1)>12))peaks.push(i);let hist={};for(let i=1;i<peaks.length;i++){let bpm=60*200/(peaks[i]-peaks[i-1]);while(bpm<60)bpm*=2;while(bpm>180)bpm/=2;if(bpm>=50&&bpm<=200){let b=Math.round(bpm);hist[b]=(hist[b]||0)+1}}let best=Object.entries(hist).sort((a,b)=>b[1]-a[1])[0];if(!best)throw Error('bpm');let bpm=+best[0];bpmCache[t.id]=bpm;localStorage.setItem('dvniel-bpm',JSON.stringify(bpmCache));$('#bpm').textContent=bpm;render();status('BPM ESTIMADO · GRABACIÓN ANTIGUA',false);ctx.close()}catch(e){status('BPM NO DISPONIBLE PARA ESTA PISTA',false)}};
